version: '3.8'

services:
  web:
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0' -p '8888'"
    volumes:
      - .:/d_runner
    ports:
      - 8888:8888
    tty: true
    stdin_open: true
    env_file:
      - spec/dummy/.env

networks:
  default:
    external:
      name: dev-net
